name: Adam Chan Media
favicon: null
layout_spectrum: 0.7109471266157925
typography_spectrum: 0.1435014856979251
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.25773634924553335
  lightness: 0.6537050236947834
  saturation: 0.16452691261656582
  rhythmicContrast: 0.4610471432097256
purpose: []
