name: Adam Chan Media
favicon: null
layout_spectrum: 0.01064
typography_spectrum: 0.76667
title: Portfolio of Adam J Chan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#fec878'
    - '#525252'
    - '#b59056'
  brandStrength: 0
  lightness: 0.9375
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
