name: Adam Chan Media
favicon: null
layout_spectrum: 0.76022
typography_spectrum: 0.76667
title: Portfolio of Adam Chan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#fec878'
    - '#525252'
    - '#b59056'
  brandStrength: 0.375
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
